service: KeywordScanner
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-2

plugins:
  - serverless-offline

functions:
  scanner:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: post
  # you can overwrite defaults here
  #  stage: dev
# you can define service wide environment variables here
#  environment:
#    AZURE_SUBSCRIPTION_KEY: "f9a81dda603b4cab97e7641ae0231f71"

#    Define function environment variables here
#    environment:
#      variable2: value2
